# placeholder definitions for model kernels
# model-specific versions generated by codegen.jl from user-provided models
Q(θ,α,μ,t) = throw(ModelDefError(θ))
R(θ,α,μ,t) = throw(ModelDefError(θ))

Q!(out,θ,α,μ,t) = throw(ModelDefError(θ))
R!(out,θ,α,μ,t) = throw(ModelDefError(θ))

f(θ,x,u,t) = throw(ModelDefError(θ))
fx(θ,x,u,t) = throw(ModelDefError(θ))
fu(θ,x,u,t) = throw(ModelDefError(θ))
fxx(θ,x,u,t) = throw(ModelDefError(θ))
fxu(θ,x,u,t) = throw(ModelDefError(θ))
fuu(θ,x,u,t) = throw(ModelDefError(θ))

f!(out,θ,x,u,t) = throw(ModelDefError(θ))
fx!(out,θ,x,u,t) = throw(ModelDefError(θ))
fu!(out,θ,x,u,t) = throw(ModelDefError(θ))
fxx!(θ,x,u,t) = throw(ModelDefError(θ))
fxu!(θ,x,u,t) = throw(ModelDefError(θ))
fuu!(θ,x,u,t) = throw(ModelDefError(θ))

l(θ,x,u,t) = throw(ModelDefError(θ))
lx(θ,x,u,t) = throw(ModelDefError(θ))
lu(θ,x,u,t) = throw(ModelDefError(θ))
lxx(θ,x,u,t) = throw(ModelDefError(θ))
lxu(θ,x,u,t) = throw(ModelDefError(θ))
luu(θ,x,u,t) = throw(ModelDefError(θ))

l!(out,θ,x,u,t) = throw(ModelDefError(θ))
lx!(out,θ,x,u,t) = throw(ModelDefError(θ))
lu!(out,θ,x,u,t) = throw(ModelDefError(θ))
lxx!(θ,x,u,t) = throw(ModelDefError(θ))
lxu!(θ,x,u,t) = throw(ModelDefError(θ))
luu!(θ,x,u,t) = throw(ModelDefError(θ))

m(θ,x,u,t) = throw(ModelDefError(θ))
mx(θ,x,u,t) = throw(ModelDefError(θ))
mxx(θ,x,u,t) = throw(ModelDefError(θ))

m!(out,θ,x,u,t) = throw(ModelDefError(θ))
mx!(out,θ,x,u,t) = throw(ModelDefError(θ))
mxx!(out,θ,x,u,t) = throw(ModelDefError(θ))

Lxx(θ,λ,x,u,t) = throw(ModelDefError(θ))
Lxu(θ,λ,x,u,t) = throw(ModelDefError(θ))
Luu(θ,λ,x,u,t) = throw(ModelDefError(θ))

Lxx!(out,θ,λ,x,u,t) = throw(ModelDefError(θ))
Lxu!(out,θ,λ,x,u,t) = throw(ModelDefError(θ))
Luu!(out,θ,λ,x,u,t) = throw(ModelDefError(θ))
